security:
  oauth2:
    client:
      clientId: auth-service

server:
#  servlet:
#    contextPath: /auth
  port: 1000
logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: appuser
    password: test123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost
