spring:
  application:
    name: finance-service

server:
  port: 8301

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

security:
  oauth2:
    client:
      clientId: finance-service
      clientSecret: ${FINANCE_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:9000/api/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:9000/api/auth/user/info

alphavantage:
  apikey: FKJEFKEW
