security:
  oauth2:
    client:
      clientId: auth-service

server:
  contextPath: /auth
  port: 1000
logging:
  level:
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: appuser
    password: test123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

